### ISSUE TITLE
Giving clear hint of the renaming

### ISSUE THREAD

**Issue by Zeng-Lecheng** [DALPy-Developers/DALPy#14]
**Is your feature request related to a problem? Please describe.**
Yes it is a problem. I was installing cormen-lib today and found my code not working at all. The `import cormen_lib` statement threw an `ModuleNotFoundError` to me which led me to troubleshoot on my Python installation. After 20 minutes of configuring and reinstalling cormen-lib and Python and even my IDE back and forth, I finally saw your PyPI page and realized that the project was renamed.

**Describe the solution you'd like**
Giving clear hints of the renaming is much better, instead of removing all the code under the name `cormen_lib` and throwing `ModuleNotFoundError`. We could have a print statement in `cormen_lib.py`: `print('cormen_lib is renamed to dalpy. See https://github.com/DALPy-Developers/DALPy for detail')`, as well as all the names of the classes in the library. When users try to import something from cormen_lib (e.g. running their previous homework), they would know what to do to solve it.

**Comment by EitanJoseph** [comment]
Thank you for opening the bug report! This issue has been resolved. You should uninstall the cormen-lib version you have just previously installed (1.1.2), and reinstall the current version (1.1.3). You should now be able to still use existing code using the `cormen-lib` module.

1. `pip uninstall cormen-lib`
2. `pip install cormen-lib`
