### ISSUE TITLE
Add a warning when students return a value from a function being evaluated with in-place=True

### ISSUE THREAD

**Issue by EitanJoseph** [DALPy-Developers/DALPy#2]
**Is your feature request related to a problem? Please describe.**
Some problems may take a data structure as input, passed by reference, to be updated by a function implemented by a student. In these situations, [`test_utils.run_generic_test`](https://cormen-lib-developers.github.io/Cormen-Lib/test_utils.html#cormen_lib.test_utils.run_generic_test) offers an optional parameter `in_place` that if set to True causes the test case to compare the expected against the input parameter. Any returned value from the tested function will then get discarded, which can cause confusion for students who believe that the function should have a return type. 

**Describe the solution you'd like**
In the case that a student has a function return a non-None value when the `in_place` flag is set to True, a warning could appear to indicate to the student that they should be updating the input parameter by reference instead of returning a new value. Another option could be to allow for the distinction between a "return comparator" and "parameter comparator", which both need to be satisfied. This could also be used for the dual purpose of ensuring that an input data structure is not altered when it should not be (for example the accidental destruction of a queue).

**Describe alternatives you've considered**
The only way to clarify this at the moment is to add a note to the problem description (in English) explaining that the input should be updated, and no return type is required for such problems.

**Additional context**
Reported by a student in Brandeis University COSI21a of Spring 2022

**Comment by ChamiLamelas** [comment]
Resolved with commit: 

Version 1.0.4: Added UnexpectedReturnWarning when users return values from functions being evaluated in an in-place=True context
