### ISSUE TITLE
GraphEdgeError message does not use dalpy_to_string for vertices.

### ISSUE THREAD

**Issue by EitanJoseph** [DALPy-Developers/DALPy#24]
**Describe the bug**
The `GraphEdgeError` class does not produce a readable output. This is because the vertices are not displayed properly with their data.  An example output:

```dalpy.graphs.GraphEdgeError: graph does not have an edge from a vertex with name <dalpy.graphs.Vertex object at 0x7faa24830340> to a vertex with name <dalpy.graphs.Vertex object at 0x7faa24833670>```

**To Reproduce**
1. `g = Graph()`
2. `v1 = Vertex("a")`
3. `v2 = Vertex("b")`
4. `g.add_vertex(v1)`
5. `g.add_vertex(v2)`
6. `g.weight(v2, v1)`
7. Observe the error message.

**Expected behavior**
The output should display the `Vertex` objects using the data of the vertex.

**Comment by ChamiLamelas** [comment]
I think `Vertex:get_name()` could also be used here.
